#!/usr/bin/env bash
# Borrowed from the s2n-bignum project
# https://github.com/awslabs/s2n-bignum/blob/main/arm/proofs/simulator.c
# Author(s): John Harrison, Juneyoung Lee
set -e
set -o xtrace

# cd Arm/Insts/Cosim

OUTFILE=$(mktemp)
echo "using tempfile ${OUTFILE}"

cat template.S | sed -e "s/ICODE/$1/" > "${OUTFILE}.S"
gcc -c "${OUTFILE}.S" 
gcc -o "${OUTFILE}.out" simulator.c "${OUTFILE}.o"

shift 1
./"{OUTFILE}.out" "$@"

# rm ${OUTFILE}.out ${OUTFILE}.S 

####  rm *.o simulator
